In [1]:
import pandas as pd
import numpy as np

In [29]:
# Прочитайте файл 2017_jun_final.csv за допомогою методу read_csv
df = pd.read_csv('2017_jun_final - 2017_jun_final.csv')
df

,N,Посада,Мова програмування,Спеціалізація,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,...,Ще студент,Рівень англійської,Предметна область,Дата заповнення,User.Agent,exp,current_job_exp,salary,Валюта,cls
0,1,Junior QA engineer,NaN,Manual QA,0.5,0.5,400,0,Харків,до 10 осіб,...,True,Pre-intermediate (нище середнього),"iOS,eCommerce",12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN,QA
1,2,Junior QA engineer,NaN,Manual QA,менше 3 місяців,менше 3 місяців,430,130,Харків,більше 1000 осіб,...,True,Upper-Intermediate (вище середнього),Веб-розробка,12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430,NaN,QA
2,3,Software Engineer,C#/.NET,NaN,4,1,2500,800,Київ,до 1000 осіб,...,False,Intermediate (середній),"Веб-розробка,Корпоративні системи",12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,NaN,DEV
3,4,Software Engineer,JavaScript,NaN,5,4,2000,400,Одеса,до 200 осіб,...,False,Pre-intermediate (нище середнього),"Desktop Applications,Веб-розробка",12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,NaN,DEV
4,5,Senior Software Engineer,JavaScript,NaN,10 і більше років,0.5,4500,500,Інше,до 10 осіб,...,False,Intermediate (середній),"Desktop Applications,Веб-розробка",12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,NaN,DEV
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8699,8700,QA engineer,NaN,Manual QA,1,менше 3 місяців,700,700,Одеса,до 50 осіб,...,False,Intermediate (середній),"Android,Desktop Applications",12/07/2017 15:45:24,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....,1.0,0.0,700,NaN,QA
8700,8701,Marketing,NaN,NaN,0.5,0.5,400,120,Київ,до 50 осіб,...,False,Pre-intermediate (нище середнього),eCommerce,12/07/2017 17:00:06,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN,NaN
8701,8702,Junior Software Engineer,Ruby/Rails,NaN,1,0.5,800,500,Львів,до 10 осіб,...,False,Upper-Intermediate (вище середнього),"Веб-розробка,Корпоративні системи",12/07/2017 17:32:26,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,0.5,800,NaN,DEV
8702,8703,Team lead,NaN,NaN,6,4,2600,0,Дніпро,більше 1000 осіб,...,False,Advanced (просунутий),Фінанси та банкінг,12/07/2017 18:14:59,Mozilla/5.0 (Windows NT 6.1) AppleWebKit/537.3...,6.0,4.0,2600,NaN,PM
8703,8704,Senior Software Engineer,Java,NaN,7,2,5000,800,Одеса,до 1000 осіб,...,False,Upper-Intermediate (вище середнього),Веб-розробка,12/07/2017 21:28:57,Mozilla/5.0 (iPad; CPU OS 10_3_2 like Mac OS X...,7.0,2.0,5000,NaN,DEV

In [12]:
# Прочитайте отриману таблицю, використовуючи метод head
df.head()

,N,Посада,Мова програмування,Спеціалізація,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,...,Ще студент,Рівень англійської,Предметна область,Дата заповнення,User.Agent,exp,current_job_exp,salary,Валюта,cls
0,1,Junior QA engineer,NaN,Manual QA,0.5,0.5,400,0,Харків,до 10 осіб,...,True,Pre-intermediate (нище середнього),"iOS,eCommerce",12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400,NaN,QA
1,2,Junior QA engineer,NaN,Manual QA,менше 3 місяців,менше 3 місяців,430,130,Харків,більше 1000 осіб,...,True,Upper-Intermediate (вище середнього),Веб-розробка,12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430,NaN,QA
2,3,Software Engineer,C#/.NET,NaN,4,1,2500,800,Київ,до 1000 осіб,...,False,Intermediate (середній),"Веб-розробка,Корпоративні системи",12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500,NaN,DEV
3,4,Software Engineer,JavaScript,NaN,5,4,2000,400,Одеса,до 200 осіб,...,False,Pre-intermediate (нище середнього),"Desktop Applications,Веб-розробка",12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000,NaN,DEV
4,5,Senior Software Engineer,JavaScript,NaN,10 і більше років,0.5,4500,500,Інше,до 10 осіб,...,False,Intermediate (середній),"Desktop Applications,Веб-розробка",12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500,NaN,DEV

In [13]:
# Визначте розмір таблиці за допомогою методу shape
df.shape

(8704, 25)

In [14]:
# Визначте типи всіх стовпців за допомогою dataframe.dtypes
df.dtypes

N                                     int64
Посада                               object
Мова програмування                   object
Спеціалізація                        object
Загальний досвід роботи              object
Досвід роботи на поточному місці     object
Зарплата на місяць                    int64
Зміна зарплати за 12 місяців          int64
Місто                                object
Розмір компанії                      object
Тип компанії                         object
Стать                                object
Вік                                   int64
Освіта                               object
Університет                          object
Ще студент                             bool
Рівень англійської                   object
Предметна область                    object
Дата заповнення                      object
User.Agent                           object
exp                                 float64
current_job_exp                     float64
salary                                int64
Валюта                               object
cls                                  object
dtype: object

In [15]:
# Порахуйте, яка частка пропусків міститься в кожній колонці (використовуйте методи isnull та sum)
df.isnull().sum()

N                                      0
Посада                                 0
Мова програмування                  3850
Спеціалізація                       7219
Загальний досвід роботи                0
Досвід роботи на поточному місці       0
Зарплата на місяць                     0
Зміна зарплати за 12 місяців           0
Місто                                  0
Розмір компанії                        0
Тип компанії                           0
Стать                                  0
Вік                                    0
Освіта                                 0
Університет                          358
Ще студент                             0
Рівень англійської                     0
Предметна область                    223
Дата заповнення                        0
User.Agent                             0
exp                                    0
current_job_exp                        0
salary                                 0
Валюта                              8694
cls                                 1574
dtype: int64

In [30]:
# Видаліть усі стовпці з пропусками, крім стовпця "Мова програмування"
cols_to_delete = ['Спеціалізація', 'Університет', 'Предметна область', 'Валюта', 'cls']
df = df.drop(columns=cols_to_delete, axis=1)
df.head()

,N,Посада,Мова програмування,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,Тип компанії,Стать,Вік,Освіта,Ще студент,Рівень англійської,Дата заповнення,User.Agent,exp,current_job_exp,salary
0,1,Junior QA engineer,NaN,0.5,0.5,400,0,Харків,до 10 осіб,Аутсорсингова,жіноча,20,Неповна Вища,True,Pre-intermediate (нище середнього),12/06/2017 12:38:08,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,0.5,0.5,400
1,2,Junior QA engineer,NaN,менше 3 місяців,менше 3 місяців,430,130,Харків,більше 1000 осіб,Аутсорсингова,жіноча,21,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 12:42:51,Mozilla/5.0 (iPad; CPU OS 10_2_1 like Mac OS X...,0.0,0.0,430
2,3,Software Engineer,C#/.NET,4,1,2500,800,Київ,до 1000 осіб,Аутсорсингова,чоловіча,26,Вища,False,Intermediate (середній),12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500
3,4,Software Engineer,JavaScript,5,4,2000,400,Одеса,до 200 осіб,Продуктова,чоловіча,30,Середня,False,Pre-intermediate (нище середнього),12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000
4,5,Senior Software Engineer,JavaScript,10 і більше років,0.5,4500,500,Інше,до 10 осіб,Продуктова,чоловіча,30,Технікум / Коледж,False,Intermediate (середній),12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500

In [31]:
# Знову порахуйте, яка частка пропусків міститься в кожній колонці і переконайтеся, що залишився тільки стовпець "Мова.програмування"
df.isnull().sum()

N                                      0
Посада                                 0
Мова програмування                  3850
Загальний досвід роботи                0
Досвід роботи на поточному місці       0
Зарплата на місяць                     0
Зміна зарплати за 12 місяців           0
Місто                                  0
Розмір компанії                        0
Тип компанії                           0
Стать                                  0
Вік                                    0
Освіта                                 0
Ще студент                             0
Рівень англійської                     0
Дата заповнення                        0
User.Agent                             0
exp                                    0
current_job_exp                        0
salary                                 0
dtype: int64

In [32]:
# Видаліть усі рядки у вихідній таблиці за допомогою методу dropna
df = df.dropna()
df.head()

,N,Посада,Мова програмування,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,Тип компанії,Стать,Вік,Освіта,Ще студент,Рівень англійської,Дата заповнення,User.Agent,exp,current_job_exp,salary
2,3,Software Engineer,C#/.NET,4,1,2500,800,Київ,до 1000 осіб,Аутсорсингова,чоловіча,26,Вища,False,Intermediate (середній),12/06/2017 13:02:47,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.0,1.0,2500
3,4,Software Engineer,JavaScript,5,4,2000,400,Одеса,до 200 осіб,Продуктова,чоловіча,30,Середня,False,Pre-intermediate (нище середнього),12/06/2017 13:03:01,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,5.0,4.0,2000
4,5,Senior Software Engineer,JavaScript,10 і більше років,0.5,4500,500,Інше,до 10 осіб,Продуктова,чоловіча,30,Технікум / Коледж,False,Intermediate (середній),12/06/2017 13:03:47,Mozilla/5.0 (iPhone; CPU iPhone OS 10_3_2 like...,10.0,0.5,4500
6,7,Junior Software Engineer,C#/.NET,1,менше 3 місяців,600,100,Хмельницький,до 50 осіб,Аутсорсингова,чоловіча,23,Вища,False,Pre-intermediate (нище середнього),12/06/2017 13:04:26,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.0,0.0,600
7,8,Senior Software Engineer,C++,6,1,3300,500,Київ,до 10 осіб,Продуктова,чоловіча,28,Вища,False,Upper-Intermediate (вище середнього),12/06/2017 13:04:27,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,6.0,1.0,3300

In [19]:
# Визначте новий розмір таблиці за допомогою методу shape
df.shape

(4854, 20)

In [33]:
# Створіть нову таблицю python_data, в якій будуть тільки рядки зі спеціалістами, які вказали мову програмування Python
python_data = df[df['Мова програмування'] == 'Python']
python_data

,N,Посада,Мова програмування,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,Тип компанії,Стать,Вік,Освіта,Ще студент,Рівень англійської,Дата заповнення,User.Agent,exp,current_job_exp,salary
12,13,Software Engineer,Python,1,менше 3 місяців,800,200,Київ,до 50 осіб,Аутсорсингова,чоловіча,26,Вища,False,Pre-intermediate (нище середнього),12/06/2017 13:05:54,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,1.0,0.0,800
68,69,Software Engineer,Python,1.5,0.5,900,900,Київ,до 10 осіб,Стартап,чоловіча,21,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 13:11:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.5,0.5,900
87,88,Junior Software Engineer,Python,0.5,0.5,600,0,Київ,до 10 осіб,Аутсорсингова,чоловіча,19,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 13:12:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.5,0.5,600
114,115,Junior Software Engineer,Python,1.5,0.5,685,250,Київ,до 1000 осіб,Аутсорсингова,чоловіча,21,Неповна Вища,False,Intermediate (середній),12/06/2017 13:14:52,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.5,0.5,685
143,144,Junior Software Engineer,Python,1,1,750,250,Київ,до 10 осіб,Аутсорсингова,чоловіча,21,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 13:19:10,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,1.0,750
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8546,8547,Software Engineer,Python,5,1,2000,800,Запоріжжя,до 50 осіб,Аутсорсингова,чоловіча,22,Неповна Вища,False,Intermediate (середній),10/07/2017 14:11:26,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,5.0,1.0,2000
8625,8626,Software Engineer,Python,4,1,1750,0,Київ,більше 1000 осіб,Аутсорсингова,чоловіча,28,Середня,False,Intermediate (середній),11/07/2017 16:15:40,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....,4.0,1.0,1750
8635,8636,Senior Software Engineer,Python,10 і більше років,менше 3 місяців,4000,1300,Віддалено,до 10 осіб,Стартап,чоловіча,33,Вища,False,Upper-Intermediate (вище середнього),11/07/2017 17:51:36,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,10.0,0.0,4000
8673,8674,Junior Software Engineer,Python,0.5,0.5,350,50,Київ,до 50 осіб,Аутсорсингова,чоловіча,22,Вища,False,Intermediate (середній),12/07/2017 9:37:16,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:54....,0.5,0.5,350
8695,8696,Software Engineer,Python,1,0.5,1500,1000,Київ,до 10 осіб,Стартап,чоловіча,29,Вища,False,Intermediate (середній),12/07/2017 14:39:21,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.0,0.5,1500

In [34]:
# Визначте розмір таблиці python_data за допомогою методу shape
python_data.shape

(207, 20)

In [35]:
# Використовуючи метод groupby, виконайте групування за стовпчиком "Посада"
python_data = python_data.groupby('Посада')
python_data.head()

,N,Посада,Мова програмування,Загальний досвід роботи,Досвід роботи на поточному місці,Зарплата на місяць,Зміна зарплати за 12 місяців,Місто,Розмір компанії,Тип компанії,Стать,Вік,Освіта,Ще студент,Рівень англійської,Дата заповнення,User.Agent,exp,current_job_exp,salary
12,13,Software Engineer,Python,1,менше 3 місяців,800,200,Київ,до 50 осіб,Аутсорсингова,чоловіча,26,Вища,False,Pre-intermediate (нище середнього),12/06/2017 13:05:54,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,1.00,0.00,800
68,69,Software Engineer,Python,1.5,0.5,900,900,Київ,до 10 осіб,Стартап,чоловіча,21,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 13:11:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,1.50,0.50,900
87,88,Junior Software Engineer,Python,0.5,0.5,600,0,Київ,до 10 осіб,Аутсорсингова,чоловіча,19,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 13:12:25,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.50,0.50,600
114,115,Junior Software Engineer,Python,1.5,0.5,685,250,Київ,до 1000 осіб,Аутсорсингова,чоловіча,21,Неповна Вища,False,Intermediate (середній),12/06/2017 13:14:52,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.50,0.50,685
143,144,Junior Software Engineer,Python,1,1,750,250,Київ,до 10 осіб,Аутсорсингова,чоловіча,21,Неповна Вища,True,Upper-Intermediate (вище середнього),12/06/2017 13:19:10,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,1.00,1.00,750
153,154,Software Engineer,Python,2,1,1200,0,Дніпро,до 50 осіб,Аутстафінгова,чоловіча,34,Кандидат,False,Advanced (просунутий),12/06/2017 13:20:15,Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebK...,2.00,1.00,1200
162,163,Junior Software Engineer,Python,0.5,0.5,500,0,Вінниця,до 200 осіб,Аутсорсингова,чоловіча,20,Технікум / Коледж,True,Pre-intermediate (нище середнього),12/06/2017 13:21:08,Mozilla/5.0 (Linux; Android 7.1.2; LG-D802 Bui...,0.50,0.50,500
171,172,Junior Software Engineer,Python,0.25,0.25,800,0,Київ,до 50 осіб,Продуктова,чоловіча,25,Вища,False,Advanced (просунутий),12/06/2017 13:22:31,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,0.25,0.25,800
217,218,Software Engineer,Python,8,2,2900,150,Львів,до 1000 осіб,Аутсорсингова,чоловіча,26,Вища,False,Upper-Intermediate (вище середнього),12/06/2017 13:31:50,Mozilla/5.0 (Windows NT 6.2; Win64; x64) Apple...,8.00,2.00,2900
302,303,Senior Software Engineer,Python,10 і більше років,0.5,3500,-300,Київ,до 200 осіб,Продуктова,чоловіча,30,Вища,False,Upper-Intermediate (вище середнього),12/06/2017 13:46:24,Mozilla/5.0 (Windows NT 6.1; Win64; x64) Apple...,10.00,0.50,3500
373,374,Senior Software Engineer,Python,7,0.5,3100,1000,Дніпро,до 200 осіб,Аутсорсингова,чоловіча,30,Вища,False,Upper-Intermediate (вище середнього),12/06/2017 13:58:16,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_6...,7.00,0.50,3100
387,388,Software Engineer,Python,4,1.5,1200,0,Інше,до 10 осіб,Стартап,чоловіча,26,Вища,False,Pre-intermediate (нище середнього),12/06/2017 14:01:02,Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/53...,4.00,1.50,1200
1172,1173,Senior Software Engineer,Python,2,2,1300,800,Львів,до 50 осіб,Інша,чоловіча,20,Неповна Вища,True,Intermediate (середній),12/06/2017 17:38:00,Mozilla/5.0 (Linux; Android 6.0.1; Redmi 3S Bu...,2.00,2.00,1300
1363,1364,Senior Software Engineer,Python,10 і більше років,2,1500,1000,Віддалено,до 10 осіб,Стартап,чоловіча,35,Вища,False,Elementary (початковий),12/06/2017 19:10:01,Mozilla/5.0 (Windows NT 10.0; WOW64; rv:53.0) ...,10.00,2.00,1500
1489,1490,Senior Software Engineer,Python,4,1,3300,430,Львів,до 1000 осіб,Аутсорсингова,чоловіча,27,Вища,False,Upper-Intermediate (вище середнього),12/06/2017 20:48:17,Mozilla/5.0 (Windows NT 10.0; Win64; x64) Appl...,4.00,1.00,3300
2632,2633,Technical Lead,Python,4,1.5,3500,1000,Київ,до 50 осіб,Продуктова,чоловіча,23,Неповна Вища,False,Upper-Intermediate (вище середнього),13/06/2017 12:37:02,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_5...,4.00,1.50,3500
3145,3146,Technical Lead,Python,10 і більше років,2,1425,475,Київ,до 50 осіб,Аутсорсингова,чоловіча,43,Вища,False,Upper-Intermediate (вище середнього),13/06/2017 14:51:19,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:52....,10.00,2.00,1425
3935,3936,Technical Lead,Python,10 і більше років,0.25,3700,0,Київ,більше 1000 осіб,Аутсорсингова,чоловіча,34,Вища,False,Upper-Intermediate (вище середнього),14/06/2017 12:26:36,Mozilla/5.0 (Linux; Android 5.0; SM-N900V Buil...,10.00,0.25,3700
4323,4324,Technical Lead,Python,2,2,3300,800,Харків,до 200 осіб,Аутсорсингова,чоловіча,26,Вища,False,Intermediate (середній),15/06/2017 11:16:57,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,2.00,2.00,3300
4746,4747,Technical Lead,Python,5,3,2900,180,Дніпро,до 10 осіб,Аутстафінгова,чоловіча,26,Вища,False,Upper-Intermediate (вище середнього),16/06/2017 21:46:04,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2...,5.00,3.00,2900
5748,5749,System Architect,Python,10 і більше років,0.25,3000,0,Київ,до 50 осіб,Продуктова,чоловіча,40,Вища,False,Upper-Intermediate (вище середнього),20/06/2017 18:40:40,Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:53....,10.00,0.25,3000
8228,8229,System Architect,Python,10 і більше років,2,5000,0,Київ,до 10 осіб,Продуктова,чоловіча,31,Вища,False,Intermediate (середній),06/07/2017 19:15:05,Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_4...,10.00,2.00,5000

In [37]:
# Створіть новий DataFrame, де для згрупованих даних за стовпчиком "Посада", виконайте агрегацію даних за допомогою методу agg і знайдіть мінімальне та максимальне значення у стовпчику "Зарплата.в.місяць"

# Aggregating data using the agg method to find min and max salary
agg_python_data = python_data.agg({'Зарплата на місяць': ['min', 'max']})

# Resetting the index for better readability
agg_python_data.reset_index(inplace=True)

# Renaming the columns for better clarity
agg_python_data.columns = ['Position', 'Min Salary', 'Max Salary']
agg_python_data

                   Position  Min Salary  Max Salary
0  Junior Software Engineer         100        1250
1  Senior Software Engineer        1300        9200
2         Software Engineer         500        5400
3          System Architect        3000        5000
4            Technical Lead        1425        6200

In [38]:
# Створіть функцію fill_avg_salary, яка повертатиме середнє значення заробітної плати на місяць. Використовуйте її для методу apply та створіть новий стовпчик "avg"
def fill_avg_salary(row):
    return (row['Min Salary'] + row['Max Salary']) / 12

agg_python_data['avg'] = agg_python_data.apply(fill_avg_salary, axis=1)
agg_python_data

                   Position  Min Salary  Max Salary         avg
0  Junior Software Engineer         100        1250  112.500000
1  Senior Software Engineer        1300        9200  875.000000
2         Software Engineer         500        5400  491.666667
3          System Architect        3000        5000  666.666667
4            Technical Lead        1425        6200  635.416667

In [40]:
# Створіть описову статистику за допомогою методу describe для нового стовпчика.
agg_python_data['avg'].describe()

count      5.000000
mean     556.250000
std      283.348652
min      112.500000
25%      491.666667
50%      635.416667
75%      666.666667
max      875.000000
Name: avg, dtype: float64

In [41]:
# Збережіть отриману таблицю в CSV файл
agg_python_data.to_csv('avg_salary_python.csv')